server:
  build: server
  ports:
    - "5556:5556"
    - "5557:5557"
    - "5558:5558"
    - "5559:5559"
  volumes:
    - ./config:/spacerace/config
    - ./maps:/spacerace/maps

wait:
  build: docker-wait
  links:
    - server

frontend:
  build: frontend
  links:
    - server
  ports:
    - "8000:8000"
  volumes:
    - ./config:/spacerace/config
    - ./maps:/spacerace/maps

httpserver:
  build: httpserver
  links:
    - server
  ports:
    - "5001:5001"

